name: Caching Primes

on: 
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Prime Numbers
      run: echo 1 > data.txt

    - run: |
        gh release create v1.2.3 data.txt
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
      shell: bash
      name: Creates a release in GitHub and uploads attachments
